### PR TITLE
fix: replace perplexity AI deprecated model

### LINKED ISSUE #325: 🐛 Bug Report: Node.js Deprecated Model for the Perplexity function template
### 👟 Reproduction steps

Update: I'll be working on fixing this issue by updating the template to use a supported model. Will submit a PR shortly.

The Perplexity integration template in Appwrite Functions is currently non-functional due to its reliance on the deprecated 'mistral-7b-instruct' model.

1. Create a new function using the Perplexity AI integration template
2. Deploy the function
3. Attempt to make API calls to the deployed function
4. Observe the function's failure to process requests

### 👍 Expected behavior

- Function should successfully initialize with the Perplexity AI model
- API calls should return expected responses
- AI model should process queries and return relevant results

### 👎 Actual Behavior

- Function deployment fails or returns errors
- API calls fail due to the deprecated 'mistral-7b-instruct' model
- Unable to process any AI-related queries through the function

drawing

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

- Platform: Appwrite Cloud
- Integration: Perplexity AI
- Template Version: Current (as of issue creation)
- Function Runtime: Node.js (latest supported version)

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Nishantjain10**
## What does this PR do?

Updates the Perplexity AI integration template to use the currently supported `llama-3.1-sonar-small-128k-online` model instead of the deprecated `mistral-7b-instruct` model. This change will restore the functionality of the Perplexity integration template.

## Test Plan

As this is a model update in the template, testing can be performed by:
- Reviewing the model name matches the officially supported models from Perplexity AI documentation
- Deploying the updated template in Appwrite Cloud to verify it initializes correctly
- Testing the deployed function with sample queries

Note: I've verified the model name against the official Perplexity AI documentation: https://docs.perplexity.ai/guides/model-cards

## Related PRs and Issues

- Fixes #325

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes, I have read and understood the contributing guidelines.

### CODE REVIEW

File: node/chat-with-perplexity-ai/src/main.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default async ({ req, res, error }) => {
 
   try {
     const response = await perplexity.chat.completions.create({
-      model: 'mistral-7b-instruct',
+      model: 'llama-3.1-sonar-small-128k-online',
```
Comment (ItzNotABug) [inline node/chat-with-perplexity-ai/src/main.js:31]: is `mistral` deprecated completely that we are moving to `llama` here? I mean are there other active modals from mistral?

Comment (Nishantjain10) [reply node/chat-with-perplexity-ai/src/main.js:31]: According to the documentation I mentioned earlier, you can find it here: [Perplexity Model Cards](https://docs.perplexity.ai/guides/model-cards), these are the only models currently supported with the Perplexity API.

for similar reference questions, you can check out these links:
- [Why can't I use Mistral as a model option on Perplexity AI module?](https://community.make.com/t/why-cant-i-use-mistral-as-a-model-option-on-perplexity-ai-module/59330)
- [400 Invalid Model: Llama 3 8B Instruct - How is that possible if it is actually permitted?](https://community.make.com/t/400-invalid-model-llama-3-8b-instruct-how-is-that-possible-if-it-is-actually-permitted/53562/9)

**Review by ItzNotABug — APPROVED** [review]
